### ISSUE TITLE
Does one have to install this in addition to Rhasspy?

### ISSUE THREAD

**Issue by probonopd** [rhasspy/rhasspy-dialogue-hermes#1]
I have installed Rhasspy in a Docker container as described in https://rhasspy.readthedocs.io/en/latest/installation/#docker. Now I want it to speak text back at the user, e.g., to answer the question "what time is it?". Do I need to install yet another Docker container for this, and wouldn't that be inefficient regarding RAM usage, especially on memory constrained embedded devices?

**Comment by synesthesiam** [comment]
No, this will be needed only when Rhasspy 2.5 comes out. For the current 2.4 series, I would recommend using NodeRED and the [websocket API](https://rhasspy.readthedocs.io/en/latest/usage/#node-red) to do dialogue interactions.

When 2.5 comes out, you will be able to send/receive MQTT messages like Snips to do back and forth dialogue.
