### ISSUE TITLE
DialogueContinueSession - not possible to get ASR audio captured

### ISSUE THREAD

**Issue by tuxedo78** [rhasspy/rhasspy-dialogue-hermes#4]
Related to https://github.com/rhasspy/rhasspy-hermes/issues/14
In handle_continue(),  AsrStartListening should be called with a send_audio_captured flag like in start_session() instead of using default value (False) which does not allow to use the feature for continued sessions.

**Comment by synesthesiam** [comment]
Got it, thanks! Should be fixed in https://github.com/rhasspy/rhasspy-dialogue-hermes/commit/360278e1ba68b8c4bfbae3725d77c5b6b710d1f5
