### ISSUE TITLE
Multiple site ids dont work with session queue

### ISSUE THREAD

**Issue by synesthesiam** [rhasspy/rhasspy-dialogue-hermes#6]
Concurrent hotword detections from different site ids will cause one of the sessions to abort and its site's hotword service to never be reactivated.

https://community.rhasspy.org/t/maybe-a-bug-with-two-satellites/1378/6

**Comment by farfade** [comment]
Hello,

Are there any news about that ? I wish I can switch on again my second satellite :)

Regards

**Comment by synesthesiam** [comment]
Pushed up the Docker image for 2.5.6 today which has new code to handle this :)

I haven't had a chance to extensively test it yet, outside of making sure it didn't break my existing examples. So let me know if you find bugs!

**Comment by farfade** [comment]
Nice, thank you very much !

I’m using the debian installer so I’ll wait for the 2.5.6 deb package and
I’ll keep you informed of my tests

Regards

Romain

Le sam. 3 oct. 2020 à 03:22, Michael Hansen <notifications@github.com> a
écrit :

**Comment by synesthesiam** [comment]
Closing issue for now. Please re-open if there are problems :)
